# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(668, 395)
        MainWindow.setMinimumSize(QtCore.QSize(200, 200))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.drop_shadow_frame = QtWidgets.QFrame(self.centralwidget)
        self.drop_shadow_frame.setStyleSheet("background-color:  rgba(6, 60, 89, 1);\n"
"border-radius: 10px;\n"
"color:#d1d1d1;\n"
"")
        self.drop_shadow_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.drop_shadow_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.drop_shadow_frame.setObjectName("drop_shadow_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.drop_shadow_frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.title_bar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.title_bar.setStyleSheet("border:none;")
        self.title_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar.setObjectName("title_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.title_bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_title = QtWidgets.QFrame(self.title_bar)
        self.frame_title.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily("Roboto Condensed Light")
        font.setPointSize(14)
        self.frame_title.setFont(font)
        self.frame_title.setStyleSheet("border:none;\n"
"border-radius: 10px;\n"
"")
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_title)
        self.verticalLayout_2.setContentsMargins(15, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_13 = QtWidgets.QLabel(self.frame_title)
        self.label_13.setMaximumSize(QtCore.QSize(451, 21))
        font = QtGui.QFont()
        font.setFamily("URW Gothic")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgba(69, 182, 73, 1);\n"
"background-color: none;\n"
"border-radius: 20px;")
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setWordWrap(True)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)
        self.horizontalLayout.addWidget(self.frame_title)
        self.frame_btns = QtWidgets.QFrame(self.title_bar)
        self.frame_btns.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame_btns.setStyleSheet("border:none;\n"
"border-radius: 10px;\n"
"")
        self.frame_btns.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns.setObjectName("frame_btns")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_btns)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.btn_minimize = QtWidgets.QPushButton(self.frame_btns)
        self.btn_minimize.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_minimize.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_minimize.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;        \n"
"    background-color: rgb(255, 170, 0);\n"
"}\n"
"QPushButton:hover {    \n"
"    background-color: rgba(255, 170, 0, 150);\n"
"}")
        self.btn_minimize.setText("")
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout_3.addWidget(self.btn_minimize)
        self.btn_close = QtWidgets.QPushButton(self.frame_btns)
        self.btn_close.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_close.setMaximumSize(QtCore.QSize(17, 17))
        self.btn_close.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 8px;        \n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:hover {        \n"
"    background-color: rgba(255, 0, 0, 150);\n"
"}")
        self.btn_close.setText("")
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_3.addWidget(self.btn_close)
        self.horizontalLayout.addWidget(self.frame_btns)
        self.verticalLayout.addWidget(self.title_bar)
        self.content_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.content_bar.setStyleSheet("")
        self.content_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_bar.setObjectName("content_bar")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.content_bar)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.content_bar)
        self.stackedWidget.setStyleSheet("background-color: none;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_home)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_content_home = QtWidgets.QFrame(self.page_home)
        self.frame_content_home.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_content_home.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content_home.setObjectName("frame_content_home")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_content_home)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_infos = QtWidgets.QFrame(self.frame_content_home)
        self.frame_infos.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_infos.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_infos.setObjectName("frame_infos")
        self.frame_circle_2 = QtWidgets.QFrame(self.frame_infos)
        self.frame_circle_2.setGeometry(QtCore.QRect(180, 0, 250, 250))
        self.frame_circle_2.setMinimumSize(QtCore.QSize(250, 250))
        self.frame_circle_2.setMaximumSize(QtCore.QSize(250, 250))
        self.frame_circle_2.setStyleSheet("QFrame{\n"
"    border: 5px solid rgb(60, 231, 195);\n"
"    border-radius: 125px;\n"
"}\n"
"QFrame:hover {\n"
"    border: 5px solid rgb(105, 95, 148);\n"
"}")
        self.frame_circle_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_circle_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_circle_2.setObjectName("frame_circle_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_circle_2)
        self.verticalLayout_7.setContentsMargins(10, 50, 10, 50)
        self.verticalLayout_7.setSpacing(10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.frame_circle_2)
        font = QtGui.QFont()
        font.setFamily("URW Gothic")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border: none;\n"
"color: rgb(60, 231, 195);")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_7.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.frame_circle_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(44)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("border: none;\n"
"color: rgb(220,220,220);")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_7.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.frame_circle_2)
        font = QtGui.QFont()
        font.setFamily("URW Gothic")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("border: none;\n"
" color: rgb(128, 102, 168);")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_7.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.frame_circle_2)
        font = QtGui.QFont()
        font.setFamily("URW Gothic")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("border: none;\n"
"color: rgb(60, 231, 195);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_7.addWidget(self.label_8)
        self.frame_circle_3 = QtWidgets.QFrame(self.frame_infos)
        self.frame_circle_3.setGeometry(QtCore.QRect(440, 40, 170, 170))
        self.frame_circle_3.setMinimumSize(QtCore.QSize(170, 170))
        self.frame_circle_3.setMaximumSize(QtCore.QSize(170, 170))
        self.frame_circle_3.setStyleSheet("QFrame{\n"
"    border: 5px solid rgb(60, 231, 195);\n"
"    border-radius: 85px;\n"
"}\n"
"QFrame:hover {\n"
"    border: 5px solid rgb(105, 95, 148);\n"
"}")
        self.frame_circle_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_circle_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_circle_3.setObjectName("frame_circle_3")
        self.label_9 = QtWidgets.QLabel(self.frame_circle_3)
        self.label_9.setGeometry(QtCore.QRect(40, 30, 91, 20))
        font = QtGui.QFont()
        font.setFamily("URW Gothic")
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("border: none;\n"
"color: rgb(60, 231, 195);")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_circle_3)
        self.label_10.setGeometry(QtCore.QRect(20, 60, 140, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(25)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("border: none;\n"
"color: rgb(220,220,220);")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_circle_3)
        self.label_11.setGeometry(QtCore.QRect(40, 100, 91, 20))
        font = QtGui.QFont()
        font.setFamily("URW Gothic")
        font.setPointSize(8)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("border: none;\n"
" color: rgb(128, 102, 168);")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_circle_3)
        self.label_12.setGeometry(QtCore.QRect(50, 120, 71, 20))
        font = QtGui.QFont()
        font.setFamily("URW Gothic")
        font.setPointSize(8)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("border: none;\n"
"color: rgb(60, 231, 195);")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.frame_circle_1 = QtWidgets.QFrame(self.frame_infos)
        self.frame_circle_1.setGeometry(QtCore.QRect(0, 40, 170, 170))
        self.frame_circle_1.setMinimumSize(QtCore.QSize(170, 170))
        self.frame_circle_1.setMaximumSize(QtCore.QSize(170, 170))
        self.frame_circle_1.setStyleSheet("QFrame{\n"
"    border: 5px solid rgb(60, 231, 195);\n"
"    border-radius: 85px;\n"
"}\n"
"QFrame:hover {\n"
"    border: 5px solid rgb(105, 95, 148);\n"
"}")
        self.frame_circle_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_circle_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_circle_1.setObjectName("frame_circle_1")
        self.label = QtWidgets.QLabel(self.frame_circle_1)
        self.label.setGeometry(QtCore.QRect(40, 30, 81, 20))
        font = QtGui.QFont()
        font.setFamily("URW Gothic")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("border: none;\n"
"color: rgb(60, 231, 195);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_circle_1)
        self.label_2.setGeometry(QtCore.QRect(30, 60, 111, 41))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(25)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border: none;\n"
"color: rgb(220,220,220);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame_circle_1)
        self.label_3.setGeometry(QtCore.QRect(50, 100, 71, 20))
        font = QtGui.QFont()
        font.setFamily("URW Gothic")
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("border: none;\n"
" color: rgb(128, 102, 168);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame_circle_1)
        self.label_4.setGeometry(QtCore.QRect(40, 120, 91, 16))
        font = QtGui.QFont()
        font.setFamily("URW Gothic")
        font.setPointSize(8)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("border: none;\n"
"color: rgb(60, 231, 195);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.frame_infos)
        self.frame_label_credits = QtWidgets.QFrame(self.frame_content_home)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_label_credits.sizePolicy().hasHeightForWidth())
        self.frame_label_credits.setSizePolicy(sizePolicy)
        self.frame_label_credits.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_label_credits.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_credits.setObjectName("frame_label_credits")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_label_credits)
        self.horizontalLayout_6.setContentsMargins(15, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_9.addWidget(self.frame_label_credits)
        self.verticalLayout_5.addWidget(self.frame_content_home)
        self.stackedWidget.addWidget(self.page_home)
        self.page_credits = QtWidgets.QWidget()
        self.page_credits.setStyleSheet("background-color:  rgba(6, 60, 89, 1);\n"
"border-radius: 10px;\n"
"color:#d1d1d1;")
        self.page_credits.setObjectName("page_credits")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_credits)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_21 = QtWidgets.QLabel(self.page_credits)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("URW Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_37.addWidget(self.label_21)
        self.verticalLayout_11.addLayout(self.horizontalLayout_37)
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_19 = QtWidgets.QLabel(self.page_credits)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("URW Gothic")
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_11.addWidget(self.label_19, 0, 1, 1, 1)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.page_credits)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_2.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_2.setSizePolicy(sizePolicy)
        self.horizontalSlider_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_2.setStyleSheet("")
        self.horizontalSlider_2.setMinimum(1)
        self.horizontalSlider_2.setMaximum(6)
        self.horizontalSlider_2.setSingleStep(1)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.gridLayout_11.addWidget(self.horizontalSlider_2, 3, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem1, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.page_credits)
        font = QtGui.QFont()
        font.setFamily("URW Gothic")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_11.addWidget(self.label_14, 3, 4, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.page_credits)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_22.sizePolicy().hasHeightForWidth())
        self.label_22.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("URW Gothic")
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_11.addWidget(self.label_22, 2, 1, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.page_credits)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("URW Gothic")
        font.setPointSize(10)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setStyleSheet("QComboBox {\n"
"    selection-background-color:  rgba(54,136,198,178);\n"
"    border-style: solid;\n"
"    border: 1px solid rgb(38,106,133);\n"
"    border-radius: 2px;\n"
"    padding: 5px;\n"
"    min-width: 75px;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: rgb(38,106,133);\n"
"    border-color: #6A6969;\n"
"}\n"
"\n"
"QComboBox:hover,\n"
"QPushButton:hover,\n"
"QAbstractSpinBox:hover,\n"
"QLineEdit:hover,\n"
"QTextEdit:hover,\n"
"QPlainTextEdit:hover,\n"
"QAbstractView:hover,\n"
"QTreeView:hover {\n"
"    border: 1px solid  rgba(54,136,198,178);\n"
"    color: #eff0f1;\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    selection-background-color: #4a4a4a;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #232629;\n"
"    border-radius: 2px;\n"
"    border: 1px solid rgb(38,106,133);\n"
"    selection-background-color: #18465d;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left-width: 0px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/qss_icons/dark/down_arrow_disabled.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on,\n"
"QComboBox::down-arrow:hover,\n"
"QComboBox::down-arrow:focus {\n"
"    image: url(:/qss_icons/dark/down_arrow.png);\n"
"}\n"
"")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_11.addWidget(self.comboBox_2, 0, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.page_credits)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("URW Gothic")
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.gridLayout_11.addWidget(self.label_23, 3, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.page_credits)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_24.sizePolicy().hasHeightForWidth())
        self.label_24.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("URW Gothic")
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout_11.addWidget(self.label_24, 4, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem2, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem3, 0, 4, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.page_credits)
        font = QtGui.QFont()
        font.setFamily("URW Gothic")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_11.addWidget(self.label_15, 2, 4, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.page_credits)
        font = QtGui.QFont()
        font.setFamily("URW Gothic")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_11.addWidget(self.label_16, 4, 4, 1, 1)
        self.horizontalSlider_3 = QtWidgets.QSlider(self.page_credits)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_3.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_3.setSizePolicy(sizePolicy)
        self.horizontalSlider_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider_3.setStyleSheet("")
        self.horizontalSlider_3.setMinimum(1)
        self.horizontalSlider_3.setMaximum(6)
        self.horizontalSlider_3.setSingleStep(1)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.gridLayout_11.addWidget(self.horizontalSlider_3, 4, 2, 1, 1)
        self.horizontalSlider = QtWidgets.QSlider(self.page_credits)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider.sizePolicy().hasHeightForWidth())
        self.horizontalSlider.setSizePolicy(sizePolicy)
        self.horizontalSlider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.horizontalSlider.setStyleSheet("")
        self.horizontalSlider.setMinimum(1)
        self.horizontalSlider.setMaximum(6)
        self.horizontalSlider.setSingleStep(1)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.gridLayout_11.addWidget(self.horizontalSlider, 2, 2, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.page_credits)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("URW Gothic")
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.gridLayout_11.addWidget(self.label_25, 1, 1, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.page_credits)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_3.sizePolicy().hasHeightForWidth())
        self.comboBox_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("URW Gothic")
        font.setPointSize(10)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setStyleSheet("QComboBox {\n"
"    selection-background-color:  rgba(54,136,198,178);\n"
"    border-style: solid;\n"
"    border: 1px solid rgb(38,106,133);\n"
"    border-radius: 2px;\n"
"    padding: 5px;\n"
"    min-width: 75px;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    background-color: rgb(38,106,133);\n"
"    border-color: #6A6969;\n"
"}\n"
"\n"
"QComboBox:hover,\n"
"QPushButton:hover,\n"
"QAbstractSpinBox:hover,\n"
"QLineEdit:hover,\n"
"QTextEdit:hover,\n"
"QPlainTextEdit:hover,\n"
"QAbstractView:hover,\n"
"QTreeView:hover {\n"
"    border: 1px solid  rgba(54,136,198,178);\n"
"    color: #eff0f1;\n"
"}\n"
"\n"
"QComboBox:on {\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"    selection-background-color: #4a4a4a;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    background-color: #232629;\n"
"    border-radius: 2px;\n"
"    border: 1px solid rgb(38,106,133);\n"
"    selection-background-color: #18465d;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    border-left-width: 0px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/qss_icons/dark/down_arrow_disabled.png);\n"
"}\n"
"\n"
"QComboBox::down-arrow:on,\n"
"QComboBox::down-arrow:hover,\n"
"QComboBox::down-arrow:focus {\n"
"    image: url(:/qss_icons/dark/down_arrow.png);\n"
"}\n"
"")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_11.addWidget(self.comboBox_3, 1, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem4, 1, 4, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_11)
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.label_20 = QtWidgets.QLabel(self.page_credits)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("URW Gothic")
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_36.addWidget(self.label_20)
        self.verticalLayout_11.addLayout(self.horizontalLayout_36)
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.theme1 = QtWidgets.QPushButton(self.page_credits)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.theme1.sizePolicy().hasHeightForWidth())
        self.theme1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(8)
        self.theme1.setFont(font)
        self.theme1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.theme1.setStyleSheet("QPushButton {\n"
"    color:white;\n"
"    border-color: #76797C;\n"
"    padding: 1px;\n"
"    border-radius: 5px;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    background-color:  rgb(0, 77, 128);\n"
"}\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/myresource/resource/single_video.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.theme1.setIcon(icon)
        self.theme1.setIconSize(QtCore.QSize(30, 30))
        self.theme1.setObjectName("theme1")
        self.horizontalLayout_35.addWidget(self.theme1)
        self.theme2 = QtWidgets.QPushButton(self.page_credits)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.theme2.sizePolicy().hasHeightForWidth())
        self.theme2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(8)
        self.theme2.setFont(font)
        self.theme2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.theme2.setStyleSheet("QPushButton {\n"
"    color:white;\n"
"    border-color: #76797C;\n"
"    padding: 1px;\n"
"    border-radius: 5px;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    background-color:  rgb(45, 45, 45);\n"
"}\n"
"\n"
"\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/myresource/resource/playlist.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.theme2.setIcon(icon1)
        self.theme2.setIconSize(QtCore.QSize(30, 30))
        self.theme2.setObjectName("theme2")
        self.horizontalLayout_35.addWidget(self.theme2)
        self.verticalLayout_11.addLayout(self.horizontalLayout_35)
        self.stackedWidget.addWidget(self.page_credits)
        self.account_page = QtWidgets.QWidget()
        self.account_page.setStyleSheet("background-color:  rgba(6, 60, 89, 1);\n"
"border-radius: 10px;\n"
"color:#d1d1d1;")
        self.account_page.setObjectName("account_page")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.account_page)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.donate_button = QtWidgets.QPushButton(self.account_page)
        self.donate_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.donate_button.setStyleSheet("QPushButton {\n"
"    padding: 3px;\n"
"    padding-right: 10px;\n"
"    padding-left: 10px;\n"
"    background-color:rgb(255, 170, 0);\n"
"    border-radius: 5px;\n"
"    color:black;\n"
"\n"
"}\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/resource/resource/paypal.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.donate_button.setIcon(icon2)
        self.donate_button.setObjectName("donate_button")
        self.verticalLayout_26.addWidget(self.donate_button)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.developer_info = QtWidgets.QTextBrowser(self.account_page)
        self.developer_info.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.developer_info.sizePolicy().hasHeightForWidth())
        self.developer_info.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("URW Gothic")
        self.developer_info.setFont(font)
        self.developer_info.setStyleSheet("")
        self.developer_info.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.developer_info.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.developer_info.setReadOnly(True)
        self.developer_info.setOpenExternalLinks(True)
        self.developer_info.setObjectName("developer_info")
        self.horizontalLayout_29.addWidget(self.developer_info)
        self.verticalLayout_26.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.warlordsoft_button = QtWidgets.QPushButton(self.account_page)
        self.warlordsoft_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.warlordsoft_button.setStyleSheet("QPushButton {\n"
"    padding: 3px;\n"
"    padding-right: 10px;\n"
"    padding-left: 10px;\n"
"    background-color:rgb(0, 153, 255);\n"
"    border-radius: 5px;\n"
"    color:black;\n"
"\n"
"}\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/resource/resource/link.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.warlordsoft_button.setIcon(icon3)
        self.warlordsoft_button.setObjectName("warlordsoft_button")
        self.horizontalLayout_34.addWidget(self.warlordsoft_button)
        self.rate_button = QtWidgets.QPushButton(self.account_page)
        self.rate_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rate_button.setStyleSheet("QPushButton {\n"
"    padding: 3px;\n"
"    padding-right: 10px;\n"
"    padding-left: 10px;\n"
"    background-color:rgb(0, 153, 255);\n"
"    border-radius: 5px;\n"
"    color:black;\n"
"\n"
"}\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/resource/resource/facebook-like.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rate_button.setIcon(icon4)
        self.rate_button.setObjectName("rate_button")
        self.horizontalLayout_34.addWidget(self.rate_button)
        self.feedback_button = QtWidgets.QPushButton(self.account_page)
        self.feedback_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.feedback_button.setStyleSheet("QPushButton {\n"
"    padding: 3px;\n"
"    padding-right: 10px;\n"
"    padding-left: 10px;\n"
"    background-color:rgb(0, 153, 255);\n"
"    border-radius: 5px;\n"
"    color:black;\n"
"\n"
"}\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/resource/resource/person-growth.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.feedback_button.setIcon(icon5)
        self.feedback_button.setObjectName("feedback_button")
        self.horizontalLayout_34.addWidget(self.feedback_button)
        self.horizontalLayout_33.addLayout(self.horizontalLayout_34)
        self.verticalLayout_26.addLayout(self.horizontalLayout_33)
        self.stackedWidget.addWidget(self.account_page)
        self.main_home = QtWidgets.QWidget()
        self.main_home.setObjectName("main_home")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.main_home)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.monitor_button = QtWidgets.QPushButton(self.main_home)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.monitor_button.sizePolicy().hasHeightForWidth())
        self.monitor_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("URW Gothic")
        font.setPointSize(10)
        self.monitor_button.setFont(font)
        self.monitor_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.monitor_button.setStyleSheet("QPushButton {\n"
"color: rgba(69, 182, 73, 1);\n"
"    border-color: #76797C;\n"
"    padding: 3px;\n"
"    border-radius: 5px;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"\n"
"\n"
"\n"
"}\n"
"QPushButton:hover {    \n"
"background-color:  rgb(0, 77, 128);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/resource/resource/severity.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.monitor_button.setIcon(icon6)
        self.monitor_button.setIconSize(QtCore.QSize(55, 60))
        self.monitor_button.setObjectName("monitor_button")
        self.gridLayout_10.addWidget(self.monitor_button, 0, 1, 1, 1)
        self.account_button = QtWidgets.QPushButton(self.main_home)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.account_button.sizePolicy().hasHeightForWidth())
        self.account_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("URW Gothic")
        font.setPointSize(10)
        self.account_button.setFont(font)
        self.account_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.account_button.setStyleSheet("QPushButton {\n"
"color: rgba(69, 182, 73, 1);\n"
"    border-color: #76797C;\n"
"    padding: 3px;\n"
"    border-radius: 5px;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"\n"
"\n"
"\n"
"}\n"
"QPushButton:hover {    \n"
"background-color:  rgb(0, 77, 128);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/resource/resource/check-male--v1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.account_button.setIcon(icon7)
        self.account_button.setIconSize(QtCore.QSize(55, 60))
        self.account_button.setObjectName("account_button")
        self.gridLayout_10.addWidget(self.account_button, 0, 3, 1, 1)
        self.setting_button = QtWidgets.QPushButton(self.main_home)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setting_button.sizePolicy().hasHeightForWidth())
        self.setting_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("URW Gothic")
        font.setPointSize(10)
        self.setting_button.setFont(font)
        self.setting_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.setting_button.setStyleSheet("QPushButton {\n"
"color: rgba(69, 182, 73, 1);\n"
"    border-color: #76797C;\n"
"    padding: 3px;\n"
"    border-radius: 5px;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"\n"
"\n"
"\n"
"}\n"
"QPushButton:hover {    \n"
"background-color:  rgb(0, 77, 128);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/resource/resource/horizontal-settings-mixer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setting_button.setIcon(icon8)
        self.setting_button.setIconSize(QtCore.QSize(55, 60))
        self.setting_button.setObjectName("setting_button")
        self.gridLayout_10.addWidget(self.setting_button, 0, 2, 1, 1)
        self.verticalLayout_29.addLayout(self.gridLayout_10)
        self.verticalLayout_30.addLayout(self.verticalLayout_29)
        self.stackedWidget.addWidget(self.main_home)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.content_bar)
        self.credits_bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.credits_bar.setMaximumSize(QtCore.QSize(16777215, 33))
        self.credits_bar.setStyleSheet("background-color: none;")
        self.credits_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.credits_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.credits_bar.setObjectName("credits_bar")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.credits_bar)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.home_button = QtWidgets.QPushButton(self.credits_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_button.sizePolicy().hasHeightForWidth())
        self.home_button.setSizePolicy(sizePolicy)
        self.home_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home_button.setStyleSheet("")
        self.home_button.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/resource/resource/circled-menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_button.setIcon(icon9)
        self.home_button.setIconSize(QtCore.QSize(40, 29))
        self.home_button.setObjectName("home_button")
        self.horizontalLayout_2.addWidget(self.home_button)
        self.speed = QtWidgets.QPushButton(self.credits_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speed.sizePolicy().hasHeightForWidth())
        self.speed.setSizePolicy(sizePolicy)
        self.speed.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.speed.setStyleSheet("")
        self.speed.setText("")
        self.speed.setIcon(icon6)
        self.speed.setIconSize(QtCore.QSize(40, 31))
        self.speed.setObjectName("speed")
        self.horizontalLayout_2.addWidget(self.speed)
        self.label_title = QtWidgets.QLabel(self.credits_bar)
        font = QtGui.QFont()
        font.setFamily("URW Gothic")
        font.setPointSize(12)
        self.label_title.setFont(font)
        self.label_title.setStyleSheet("color: rgba(69, 182, 73, 1);\n"
"text-align: center;\n"
"border:none;")
        self.label_title.setObjectName("label_title")
        self.horizontalLayout_2.addWidget(self.label_title)
        self.setting = QtWidgets.QPushButton(self.credits_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.setting.sizePolicy().hasHeightForWidth())
        self.setting.setSizePolicy(sizePolicy)
        self.setting.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.setting.setStyleSheet("")
        self.setting.setText("")
        self.setting.setIcon(icon8)
        self.setting.setIconSize(QtCore.QSize(40, 28))
        self.setting.setObjectName("setting")
        self.horizontalLayout_2.addWidget(self.setting)
        self.account = QtWidgets.QPushButton(self.credits_bar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.account.sizePolicy().hasHeightForWidth())
        self.account.setSizePolicy(sizePolicy)
        self.account.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.account.setStyleSheet("")
        self.account.setText("")
        self.account.setIcon(icon7)
        self.account.setIconSize(QtCore.QSize(40, 32))
        self.account.setObjectName("account")
        self.horizontalLayout_2.addWidget(self.account)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.verticalLayout.addWidget(self.credits_bar)
        self.verticalLayout_3.addWidget(self.drop_shadow_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_13.setText(_translate("MainWindow", "\"If you control the code, you control the world.\""))
        self.btn_minimize.setToolTip(_translate("MainWindow", "Minimize"))
        self.btn_close.setToolTip(_translate("MainWindow", "Close"))
        self.label_5.setText(_translate("MainWindow", "INTERNET SPEED"))
        self.label_6.setText(_translate("MainWindow", "8.8"))
        self.label_7.setText(_translate("MainWindow", "MB/S"))
        self.label_8.setText(_translate("MainWindow", "No Internet"))
        self.label_9.setText(_translate("MainWindow", "RAM USAGE"))
        self.label_10.setText(_translate("MainWindow", "80%"))
        self.label_11.setText(_translate("MainWindow", "Total: 16 GB"))
        self.label_12.setText(_translate("MainWindow", "Free 2.0 GB"))
        self.label.setText(_translate("MainWindow", "CPU USAGE"))
        self.label_2.setText(_translate("MainWindow", "25%"))
        self.label_3.setText(_translate("MainWindow", "CPU Info"))
        self.label_4.setText(_translate("MainWindow", "Temp: 45Cº"))
        self.label_21.setText(_translate("MainWindow", "App Settings"))
        self.label_19.setText(_translate("MainWindow", "Net Speed Unit          "))
        self.label_14.setText(_translate("MainWindow", "1"))
        self.label_22.setText(_translate("MainWindow", "Net Speed Freq          "))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "MB/s | KB/s | B/s"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "mb/s | kb/s | b/s"))
        self.label_23.setText(_translate("MainWindow", "CPU Indicator Freq          "))
        self.label_24.setText(_translate("MainWindow", "RAM Indicator Freq          "))
        self.label_15.setText(_translate("MainWindow", "1"))
        self.label_16.setText(_translate("MainWindow", "1"))
        self.label_25.setText(_translate("MainWindow", "CPU Temp Unit          "))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "°C  (Celsius)"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "°F  (Fahrenheit)"))
        self.label_20.setText(_translate("MainWindow", "Theme Settings"))
        self.theme1.setText(_translate("MainWindow", "Theme1 (Zesty-Blue)"))
        self.theme2.setText(_translate("MainWindow", "Theme2 (Grey)"))
        self.donate_button.setText(_translate("MainWindow", "Donate"))
        self.developer_info.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'URW Gothic\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/resource/resource/speedx.png\" height=\"20\" /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:10pt; color:#35a849;\">Developed by: </span><span style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:600; color:#35a849;\">Rishabh Bhardwaj</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:10pt; color:#35a849;\">Version: </span><span style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:600; color:#35a849;\">0.2 | </span><a href=\"https://snapcraft.io/search?q=rishabh\"><span style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:600; text-decoration: underline; color:#ef2929;\">Get more apps</span></a></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:10pt; color:#35a849;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:600; color:#35a849;\">Support Request:</span><span style=\" font-family:\'Ubuntu\'; font-size:10pt; color:#35a849;\">   If you like this Application, then please support the developer by donation. Your donations make me </span><span style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:600; color:#35a849;\">feel motivated</span><span style=\" font-family:\'Ubuntu\'; font-size:10pt; color:#35a849;\"> to my work. Thanks!  Expect </span><span style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:600; color:#35a849;\">new updates</span><span style=\" font-family:\'Ubuntu\'; font-size:10pt; color:#35a849;\"> in near future!</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:10pt; color:#35a849;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'Ubuntu\'; font-size:10pt; color:#35a849;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Ubuntu\'; font-size:10pt; font-weight:600; color:#35a849;\">Donor\'s Name</span><span style=\" font-family:\'Ubuntu\'; font-size:10pt; color:#35a849;\"> and Contributions will be displayed in @ </span><a href=\"https://warlordsoftwares.com/warlord_soft/our_contributors/\"><span style=\" font-family:\'Ubuntu\'; font-weight:600; text-decoration: underline; color:#ef2929;\">warlordsoft page</span></a><span style=\" font-family:\'Ubuntu\'; font-size:10pt; color:#35a849;\"> as a Thanksgiving notes!</span></p></body></html>"))
        self.warlordsoft_button.setText(_translate("MainWindow", "Visit @WarlordSoft"))
        self.rate_button.setText(_translate("MainWindow", "Rate"))
        self.feedback_button.setText(_translate("MainWindow", "Feedback"))
        self.monitor_button.setText(_translate("MainWindow", "Monitor"))
        self.account_button.setText(_translate("MainWindow", "About"))
        self.setting_button.setText(_translate("MainWindow", "Settings"))
        self.label_title.setText(_translate("MainWindow", "SpeedX™"))
import resource_rc
