name: speedx
base: core18 # the base snap is the execution environment for this snap
version: '2.0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Internet speed monitor with cpu and ram usage utility
description: |
  A linux based desktop application for Monitoring Internet speed with system moniter in cool graphics.
grade: stable # must be 'stable' to release into candidate/stable channels  / before dev use devel
confinement: strict # use 'strict' once you have the right plugs and slots / before dev use devmode

icon: snap/gui/icon.png

architectures:
  - build-on: [amd64]

apps:
  speedx:
    command: bin/desktop-launch python3 $SNAP/speedx.py
    plugs:
      - home
      - gsettings
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - x11
      - unity7
      - wayland
      - opengl
      - hardware-observe
      - network-status
    desktop: speedx.desktop

plugs:
  gsettings:
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes
  pyqt5-runtime:
    interface: content
    target: $SNAP/pyqt5-runtime
    default-provider: pyqt5-runtime


parts:
  desktop-gui:
    plugin: dump
    source: src/
    override-build: |
      snapcraftctl build
      sed -i 's|Icon=.*|Icon=${SNAP}/meta/gui/icon.png|g' ${SNAPCRAFT_PART_SRC}/speedx.desktop
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/
      cp -rf ${SNAPCRAFT_PART_SRC}/speedx.desktop ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/speedx.desktop


  snap-launcher:
    plugin: dump
    source: snap_launcher/

  speedx:
      plugin: python
      python-version: python3
      source: .
      python-packages:
        - psutil
        - py-cpuinfo
        - cryptography
        - requests
      build-attributes: [ keep-execstack ]
